### ISSUE TITLE
在docker运行server，客户端无法正常连接

### ISSUE THREAD

**Issue by zhongjiayue-sudo** [GameFrameX/GameFrameX.Server#36]
客户端无法正常连接docker运行的server，但是server本地运行可以正常连接，docker映射的端口也是确保正确的，找了很久都找不到问题，晕厥了已经，防火墙关了也不行
![Image](https://github.com/user-attachments/assets/b1ec3b73-e41a-470a-9efb-d3bb91b903a1)

![Image](https://github.com/user-attachments/assets/b16fd00f-3fd2-4e98-96f1-8f68a50d75e8)

![Image](https://github.com/user-attachments/assets/c14b010d-b9dc-4ccc-b18b-3ad8ac58af7d)

![Image](https://github.com/user-attachments/assets/ed6eff6b-8acf-400d-a427-6607d6405c3a)

![Image](https://github.com/user-attachments/assets/3148c1f1-5c5e-4462-b708-91364bbc2849)
正常测试tcp连接，本地运行server会响应tcp连接的有输出，但是docker的server就是没有输出的
![Image](https://github.com/user-attachments/assets/b75b94e6-cd59-4ed2-baba-11259ea92b3b)

**Comment by AlianBlank** [comment]
将Docker-compose.yml 中的127.0.0.1 替换为0.0.0.0 即可

**Comment by zhongjiayue-sudo** [comment]
还是不行，真的找不到问题了，好难受
![Image](https://github.com/user-attachments/assets/72cd186a-1a9d-43c5-b01c-85889e4f5f23)

Docker-compose.yml检查也没什么问题
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - backend
  gameframex:
    image: gameframex.launcher:1.0.0
    container_name: gameframex
    ports:
      # APM 端口
      - "29090:29090"
      # TCP 端口
      - "29100:29100"
      # WebSocket 端口
      - "29110:29110"
    environment:
      - ServerType=Game
      - ServerId=1000
      - APMPort=29090
      - InnerIp=0.0.0.0
      - InnerPort=29100
      - OuterIp=0.0.0.0
      - OuterPort=29100
      - MinModuleId=10
      - MaxModuleId=9999
      - WsPort=29110
      - DiscoveryCenterIp=0.0.0.0
      - DiscoveryCenterPort=10001
      - HttpCode=inner_httpcode
      - DataBaseUrl=mongodb://admin:admin@mongodb:27017?authSource=admin
      - DataBaseName=gameframex
    networks:
      - backend
    volumes:
      - "./running/hotfix:/app/hotfix"
      - "./running/json:/app/json"
      - "./running/logs:/app/logs"
networks:
  backend:
    name: gameframex-backend
    driver: bridge

**Comment by AlianBlank** [comment]
测试一下以下文件是否可以，经过我的测试是可以的
```yml
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./running/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - backend
  gameframex:
    image: gameframex/server.launcher:1.0.0
    container_name: gameframex
    ports:
      # APM 端口
      - "29090:29090"
      # TCP 端口
      - "29100:29100"
      # WebSocket 端口
      - "29110:29110"      
      # HTTP 端口
      - "28080:28080"
    environment:
      - ServerType=Game
      - ServerId=1000
      - APMPort=29090
      - InnerPort=29100
      - OuterPort=29100
      - MinModuleId=10
      - MaxModuleId=9999
      - WsPort=29110
      - HttpPort=28080
      - DiscoveryCenterIp=127.0.0.1
      - DiscoveryCenterPort=10001
      - HttpCode=inner_httpcode
      - DataBaseUrl=mongodb://admin:admin@mongodb:27017/?authSource=admin
      - DataBaseName=gameframex
    networks:
      - frontend
      - backend
    volumes:
      - "./running/hotfix:/app/hotfix"
      - "./running/json:/app/json"
      - "./running/logs:/app/logs"
      - "./running/GameAnalytics:/GameAnalytics"
networks:
  frontend:
    name: gameframex-frontend
    driver: bridge
  backend:
    name: gameframex-backend
    driver: bridge
```
